export const LIBRARY_ITEMS = {
  backgrounds: [
    { id: 'backgroundwithtabs.png', label: 'Standard' },
    { id: 'glitter.png', label: 'Glitter' },
    { id: 'mermaid.png', label: 'Mermaid' },
    { id: 'earthtones.png', label: 'Neutral' },
    { id: 'rainbow.png', label: 'Rainbow' },
    { id: 'marble.png', label: 'Marble' },
    { id: 'cheetah.png', label: 'Cheetah' },
    { id: 'gingham.png', label: 'Gingham' },
    { id: 'brownbackground.png', label: 'Brown Leather' },
    { id: 'bluebackground.png', label: 'Blue' },
    { id: 'greenbackground.png', label: 'Green' },
    { id: 'burgundybackground.png', label: 'Burgundy' },
    { id: 'lilacbackground.png', label: 'Lilac' },
  ],
  covers: [
    { id: 'standardcover.svg', label: 'Standard' },
    { id:  'glittercover.svg', label: 'Glitter' },
    { id:  'mermaidcover.svg', label: 'Mermaid' },
    { id:  'neutralcover.svg', label: 'Neutral' },
    { id:  'rainbowcover.svg', label: 'Rainbow' },
    { id:  'marblecover.svg', label: 'Marble' },
    { id:  'cheetahcover.svg', label: 'Cheetah' },
    { id:  'ginghamcover.svg', label: 'Gingham' },
    { id:  'browncover.svg', label: 'Brown Leather' },
    { id:  'bluecover.svg', label: 'Blue' },
    { id:  'greencover.svg', label: 'Green' },
    { id:  'burgundycover.svg', label: 'Burgundy' },
    { id:  'lilaccover.svg', label: 'Lilac' },
  ],
  clinical: [
    { id: 'sessionnotetemp.svg', label: 'Session Notes' },
    { id: 'billingtemp.svg', label: 'Billing Tracker' },
    { id: 'ceutrackertemp.svg', label: 'CEU Tracker' },
    { id: 'insurancetrackertemp.svg', label: 'Insurance Tracker' },
    { id:  'thoughtlogtemp.svg', label: 'Thought Log' },
    { id: 'progresstemp.svg', label: 'Progress Notes' },
    { id: 'goalplantemp.svg', label: 'Goal Planner' },
  ],
  notes: [
    { id: 'bulletnotetemp.svg', label: 'Bullet Notes' },
    { id: 'cornelltemp.svg', label: 'Cornell Notes' },
    { id: 'lineddottemp.svg', label: 'Lined Dot Notes' },
    { id: 'dotlinetemp.svg', label: 'Dot Lined Notes' },
    { id: 'notetemp.svg', label: 'Standard Notes' },
  ],
  halfPage: [
    { id: 'monselfcare.svg', label: 'Monday Week Start Self-Care Tracker' },
    { id: 'sunselfcare.svg', label: 'Sunday Week Start Self-Care Tracker' },
    { id: 'prioritytemplate.svg', label: 'Priority Planner' },
    { id: 'monstartweek.svg', label: 'Monday Week Start  Schedule' },
    { id: 'sunstartweek.svg', label: 'Sunday Week Start Schedule' },
  ],
  quarter: [
    { id: 'quarterdots.svg', label: 'Dot Grid' },
    { id: 'quartergrid.svg', label: 'Grid' },
    { id: 'quarterlists.svg', label: 'Lists' },
    { id: 'quarternotes.svg', label: 'Notes' },
    { id: 'quartertodo.svg', label: 'To Do' },
  ],
  eighth: [
    { id: 'hometodo.svg', label: 'Home To Do' },
    { id: 'worktodo.svg', label: 'Work To Do' },
    { id: 'monstartminimonth.svg', label: 'Monday Start Mini Month' },
    { id: 'sunstartminimonth.svg', label: 'Sunday Start Mini Month' },
    { id: 'monstarttracker.svg', label: 'Monday Start Tracker' },
    { id: 'sunstartminimonth.svg', label: 'Sunday Start Tracker' },
    { id: 'smalldotgrid.svg', label: 'Dot Grid' },
    { id: 'smallgrid.svg', label: 'Grid' },
    { id: 'smallhabittracker.svg', label: 'Habit Tracker' },
    { id: 'smallmoodtracker.svg', label: 'Mood Tracker' },
    { id: 'smallreminder.svg', label: 'Reminder' },
    { id: 'smallwatertracker.svg', label: 'Water Tracker' },
    { id: 'toppriorities.svg', label: 'Top Priorities' },
  ],
};
